// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3mcWG_p7COIhlwlp8wW0HbvlJ9E6KOlw',
    appId: '1:765053941387:web:c32b1e7c56177e61eb468e',
    messagingSenderId: '765053941387',
    projectId: 'cateyepos',
    authDomain: 'cateyepos.firebaseapp.com',
    storageBucket: 'cateyepos.firebasestorage.app',
    measurementId: 'G-CKSF5YQVS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChL8SAIkD0AZ7cPuUFPOJtTxA7_23otIg',
    appId: '1:765053941387:android:e8f05ec3c1f40bbceb468e',
    messagingSenderId: '765053941387',
    projectId: 'cateyepos',
    storageBucket: 'cateyepos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQxxbS3g2FREnj-c6ApBquicaySFRwFVw',
    appId: '1:765053941387:ios:dd4fd0551a4ebb98eb468e',
    messagingSenderId: '765053941387',
    projectId: 'cateyepos',
    storageBucket: 'cateyepos.firebasestorage.app',
    iosBundleId: 'com.example.cateyePos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQxxbS3g2FREnj-c6ApBquicaySFRwFVw',
    appId: '1:765053941387:ios:dd4fd0551a4ebb98eb468e',
    messagingSenderId: '765053941387',
    projectId: 'cateyepos',
    storageBucket: 'cateyepos.firebasestorage.app',
    iosBundleId: 'com.example.cateyePos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3mcWG_p7COIhlwlp8wW0HbvlJ9E6KOlw',
    appId: '1:765053941387:web:b17aef78db2ebc05eb468e',
    messagingSenderId: '765053941387',
    projectId: 'cateyepos',
    authDomain: 'cateyepos.firebaseapp.com',
    storageBucket: 'cateyepos.firebasestorage.app',
    measurementId: 'G-WSDY7YG4B7',
  );
}
